### Get All Users

GET http://localhost:3000/api/v1/user
Accept: application/json

### Create New User
POST http://localhost:3000/api/v1/user
Content-Type: application/json
Accept: application/json

{
  "name": "testcreate",
  "email": "salah",
  "address": "Pemalang"
}

### Get User By Id

GET http://localhost:3000/api/v1/user/7
Accept: application/json

### Update User Email By Id

PUT http://localhost:3000/api/v1/user/7
Content-Type: application/json
Accept: application/json

{
  "email": "update@example.com"
}

### Delete User By Id

DELETE http://localhost:3000/api/v1/user/4
Content-Type: application/json
Accept: application/json
